### ISSUE TITLE
Use bash everywhere?

### ISSUE THREAD

**Issue by apjanke** [fieldtrip/automation#2]
Some of the shell scripts use `bash` and some use plain `sh`. What do you think about using `bash` everywhere? That would let you use the `[[ ... ]]` construct instead of `[ .. ]`, which is more robust about quoting and produces nicer error messages when something goes wrong.

`bash` is available just about everywhere these days, so requiring it shouldn't be a problem.

**Comment by robertoostenveld** [comment]
Agreed, they should now al use bash. The use of sh is only for historical reasons.
